---
- name: Gather FRR facts
  hosts: frr
  gather_facts: false

  tasks:
    - name: Get hostname
      ansible.netcommon.cli_command:
        command: hostname
      register: hostname_out

    - name: Show hostname
      debug:
        msg: "Hostname: {{ hostname_out.stdout }}"
